spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: bestuser
    password: bestuser
    jpa:
      hibernate:
        ddl-auto: validate
#  jpa:
#    show-sql: true

blog:
  title: HowCode
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Ильмир Байчурин
  copyrightFrom: 2020