spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: bestuser
    password: bestuser
    jpa:
      hibernate:
        ddl-auto: validate
  flyway:
    schemas: blog_db